#!/bin/bash
echo "🔍 Starting FocusWatch..."
echo "Note: This requires Xcode to be installed."
echo ""
echo "To install Xcode:"
echo "1. Open Mac App Store"
echo "2. Search for 'Xcode'"
echo "3. Click 'Get' or 'Install'"
echo ""
echo "Or download from: https://developer.apple.com/xcode/"
echo ""
echo "After installing Xcode:"
echo "1. Double-click FocusWatch.xcodeproj"
echo "2. Press ⌘R to build and run"
echo "3. Look for the eye icon in your menu bar"